version: '2'
services:
  zookeeper:
    image: jplock/zookeeper
    extra_hosts:
      - "portal.xd.dit72:172.16.0.4"
      - "nacos.xd.dit72:172.16.0.4"
      - "redis.xd.dit72:172.16.0.4"
      - "auth.xd.dit72:172.16.0.4"
      - "mysql.xd.dit72:172.16.0.4"
    networks:
      - ditcloud
  disconf:
    image: bailaohe/disconf
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
    volumes:
      - ./disconf/conf:/disconf/conf
    extra_hosts:
      - "portal.xd.dit72:172.16.0.4"
      - "nacos.xd.dit72:172.16.0.4"
      - "redis.xd.dit72:172.16.0.4"
      - "auth.xd.dit72:172.16.0.4"
      - "mysql.xd.dit72:172.16.0.4"
    networks:
      - ditcloud
  nginx:
    image: nginx
    ports:
      - "9999:9999" 
    volumes:
      - ./disconf/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/html
    depends_on:
      - disconf
    extra_hosts:
      - "portal.xd.dit72:172.16.0.4"
      - "nacos.xd.dit72:172.16.0.4"
      - "redis.xd.dit72:172.16.0.4"
      - "auth.xd.dit72:172.16.0.4"
      - "mysql.xd.dit72:172.16.0.4"
    networks:
      - ditcloud

networks:
  ditcloud:
