version: '2'
services:
  zookeeper:
    image: jplock/zookeeper
    networks:
      - ditcloud
  disconf:
    image: bailaohe/disconf
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
    networks:
      - ditcloud
  nginx:
    image: nginx
    ports:
      - "9999:9999" 
    volumes:
      - ./disconf/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/html
    depends_on:
      - disconf
    networks:
      - ditcloud
